baseurl = "https://trestleschiropractic.com/"
languageCode = "en-us"
languageLang = "en"
title = "Trestles Chiropractic | San Clemente Chiropractor"

# SEO Configuration
enableRobotsTXT = true
canonifyURLs = true

# Sitemap Configuration
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

